metric: COCO
num_classes: 10

TrainDataset:
  name: COCODataSet
  image_dir: VisDrone2019-DET-train/images
  anno_path: annotations/instances_train.json
  dataset_dir: dataset/visdrone
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: VisDrone2019-DET-val/images
  anno_path: annotations/instances_val.json
  dataset_dir: dataset/visdrone
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/instances_val.json
  dataset_dir: dataset/visdrone
